version: "3.9"
services:

  # Front 
  front:
    build: ./frontend/plantlib
    ports:
      - "8080:80"

  #Nginx Service
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links: 
      - front

