version: "3.9"

services:

  # Backend
  back: 
    build: ./backend/PlantLib
    command: /usr/local/bin/gunicorn PlantLib.wsgi:application --bind 0.0.0.0:8000 --timeout 90 --workers=2
    volumes: 
      - ./backend/PlantLib/:/usr/src/app
      - /static:/static
    expose: 
      - 8000
    restart: always

  # Frontend 
  front:
    build: ./frontend/plantlib
    ports:
      - "8080:80"

  # Nginx 
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    restart: always
    links: 
      - front
    volumes:
      - /static:/static
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Let's encrypt
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # Database
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=plantlib

volumes:
  postgres_data:



# https://mindsers.blog/post/https-using-nginx-certbot-docker/
