version: '3'
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DEBUG=1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: npm run serve
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend/plantlib/dist:/usr/share/nginx/html
      # - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
    depends_on:
      - frontend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw